spring:
  application:
    name: backend
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret-key: local-development-secret-key-1234567890

storage:
  upload-dir: uploads
